#!/bin/bash

cd $(dirname "$0")
config_dir="${PWD##$HOME/}"

config_backup_dir="backup-$(date +%F-%H-%M-%S)";

install_file() {
	if [[ -e "$HOME/$2" || -L "$HOME/$2" ]]; then
		if [ "$(readlink "$HOME/$2")" != "$1" ]; then
			mkdir -p  "$(dirname "$config_backup_dir/$2")"
			mv "$HOME/$2" "$config_backup_dir/$2"
			echo "'$2' already exists. It is moved to '$config_dir/$config_backup_dir/$2'." 1>&2
		else
			return
		fi
	fi
	ln -s "$1" "$HOME/$2"
}

install_config_dir_symlink() {
	if [[ -e "$HOME/.config/$1" || -L "$HOME/.config/$1" ]]; then
		readlink "$HOME/.config/$1"
		if [ "$(readlink "$HOME/.config/$1")" != "../$config_dir/config/$1" ]; then
			mkdir -p "$config_backup_dir"
			mv "$HOME/.config/$1" "$config_backup_dir/$1"
			echo "'$1' already exists. It is moved to '$config_dir/$config_backup_dir/$1'." 1>&2
		else
			return
		fi
	fi
	mkdir -p "$HOME/.config"
	ln -s "../$config_dir/config/$1" "$HOME/.config/$1"
}


# Install configuration files.
install_file "$config_dir/home/gtkrc-2.0" ".gtkrc-2.0"
for file in config/autostart/*; do
	install_file "../../$config_dir/$file" ".config/autostart/${file##*/}"
done

for dir in hypr waybar dunst gtk-3.0; do
	install_config_dir_symlink "$dir"
done


if ! command -v dunst > /dev/null; then
	echo "Did not find `dunst` in PATH"
fi

if ! command -v waybar > /dev/null; then
	echo "Did not find `waybar` in PATH"
fi
