#!/bin/bash

cd "$HOME"

# Include /etc/X11/xinit/xinitrc.d snippets.
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR:-/run/user/$UID}/gnupg/S.gpg-agent.ssh"

xrdb .Xresources &
gpg-connect-agent UPDATESTARTUPTTY /bye > /dev/null &
dex -a &
exec xmonad
