#!/bin/bash

cd "$HOME"

# Include /etc/X11/xinit/xinitrc.d snippets.
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

[ -z "$XDG_RUNTIME_DIR" ] && XDR_RUNTIME_DIR="/run/user/$UID"

if command -v gpg-agent > /dev/null; then
	gpg-agent --daemon --enable-ssh-support > /dev/null 2>&1 &
	export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"
fi

xrdb .Xresources &
dex -a &
exec qtile
