Ctrl+j cycle secondary-sid
Ctrl+J cycle secondary-sid down
Shift+L cycle-values loop-playlist inf no
Ctrl+l cycle-values loop-file inf no
Ctrl+Shift+Right cycle-values video-rotate 0 90 180 270
Ctrl+Shift+Left cycle-values video-rotate 0 270 180 90
